language: go
go:
  - 1.7.x
  - 1.8.x

go_import_path: github.com/google/pprof

os:
  - linux
  - osx

before_install:
  - go get -u github.com/golang/lint/golint honnef.co/go/tools/cmd/...

script:
  - gofmtdiff=$(gofmt -s -d .) && if [ -n "$gofmtdiff" ]; then printf 'gofmt -s found:\n%s\n' "$gofmtdiff" && exit 1; fi
  - golintlint=$(golint ./...) && if [ -n "$golintlint" ]; then printf 'golint found:\n%s\n' "$golintlint" && exit 1; fi
  - go tool vet -all .
  - gosimple ./...
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
