language: go
go:
  - 1.7.x
  - 1.8.x

before_install:
  - go get -u github.com/golang/lint/golint honnef.co/go/tools/cmd/...

script:
  - gofmtdiff=$(gofmt -s -d .) && if [ -n "$gofmtdiff" ]; then printf 'gofmt -s found:\n%s\n' "$gofmtdiff" && exit 1; fi
  - golintlint=$(golint ./...) && if [ -n "$golintlint" ]; then printf 'golint found:\n%s\n' "$golintlint" && exit 1; fi
  - go tool vet -all .
  - gosimple ./...
  - staticcheck ./...
  - unused ./...
  - go test -v ./...
  - go test -v -race ./...
